# Generated by Django 5.1.3 on 2024-11-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(help_text='Enter the album name.', max_length=200)),
                ('release_date', models.DateField(help_text="Enter the album's release date.")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], help_text='Rate the album (1 to 5 stars).')),
                ('musician', models.ForeignKey(help_text='Select the musician who released this album.', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musician_app.musician')),
            ],
        ),
    ]
