# Generated by Django 5.1.3 on 2024-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='task_model',
            field=models.ManyToManyField(blank=True, to='task_model.taskmodel'),
        ),
    ]
